# keystore.properties template
# Copy this file into a new file 'keystore.properties',
# if you want to build the .aab file locally for the android deployment
storeFile=../upload.jks
storePassword=enter-your-password-here
keyAlias=upload
keyPassword=enter-your-password-here
